// Generated by gencpp from file ls01b_v2/resolution.msg
// DO NOT EDIT!


#ifndef LS01B_V2_MESSAGE_RESOLUTION_H
#define LS01B_V2_MESSAGE_RESOLUTION_H

#include <ros/service_traits.h>


#include <ls01b_v2/resolutionRequest.h>
#include <ls01b_v2/resolutionResponse.h>


namespace ls01b_v2
{

struct resolution
{

typedef resolutionRequest Request;
typedef resolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct resolution
} // namespace ls01b_v2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ls01b_v2::resolution > {
  static const char* value()
  {
    return "e7c237841da6430c0287676ce81f71be";
  }

  static const char* value(const ::ls01b_v2::resolution&) { return value(); }
};

template<>
struct DataType< ::ls01b_v2::resolution > {
  static const char* value()
  {
    return "ls01b_v2/resolution";
  }

  static const char* value(const ::ls01b_v2::resolution&) { return value(); }
};


// service_traits::MD5Sum< ::ls01b_v2::resolutionRequest> should match 
// service_traits::MD5Sum< ::ls01b_v2::resolution > 
template<>
struct MD5Sum< ::ls01b_v2::resolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ls01b_v2::resolution >::value();
  }
  static const char* value(const ::ls01b_v2::resolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ls01b_v2::resolutionRequest> should match 
// service_traits::DataType< ::ls01b_v2::resolution > 
template<>
struct DataType< ::ls01b_v2::resolutionRequest>
{
  static const char* value()
  {
    return DataType< ::ls01b_v2::resolution >::value();
  }
  static const char* value(const ::ls01b_v2::resolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ls01b_v2::resolutionResponse> should match 
// service_traits::MD5Sum< ::ls01b_v2::resolution > 
template<>
struct MD5Sum< ::ls01b_v2::resolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ls01b_v2::resolution >::value();
  }
  static const char* value(const ::ls01b_v2::resolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ls01b_v2::resolutionResponse> should match 
// service_traits::DataType< ::ls01b_v2::resolution > 
template<>
struct DataType< ::ls01b_v2::resolutionResponse>
{
  static const char* value()
  {
    return DataType< ::ls01b_v2::resolution >::value();
  }
  static const char* value(const ::ls01b_v2::resolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LS01B_V2_MESSAGE_RESOLUTION_H
